import { readFile } from 'node:fs/promises';
import { afterEach, expect, test } from 'vitest';
import { JSDOM } from 'jsdom';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const windows = [];
function render() {
  const dom = new JSDOM(html, { runScripts: 'dangerously', url: 'http://localhost/', beforeParse(window) {
    window.scrollTo = () => {};
    window.prompt = () => null;
    window.localStorage.setItem('treino_hibrido_juarez_v5', JSON.stringify({ profile: { weight_kg: '79', waist_cm: '98' }, sessions: [] }));
  }});
  windows.push(dom.window); return dom;
}
function noConstraints(el) { return el.type !== 'number' && !el.hasAttribute('pattern') && !el.hasAttribute('min') && !el.hasAttribute('step'); }
afterEach(() => { while (windows.length) windows.pop().close(); });

// SPECSFY: US-006 FR-015 NFR-006 AC-028 TC-009
test('AC-028 carga real usa decimal e preserva texto', () => { const { window } = render(); window.startWorkoutByKey('segunda'); const el = window.document.querySelector('.set-input-group--load input'); expect(el).not.toBeNull(); const before = el.value; expect(el.inputMode).toBe('decimal'); expect(noConstraints(el)).toBe(true); expect(el.value).toBe(before); });
// SPECSFY: US-006 FR-015 NFR-006 AC-029 TC-010
test('AC-029 repetições reais usam numeric e texto livre', () => { const { window } = render(); window.startWorkoutByKey('segunda'); const group = [...window.document.querySelectorAll('.set-input-group')].find((e) => /repet/i.test(e.textContent)); expect(group).not.toBeNull(); const el = group.querySelector('input'); expect(el).not.toBeNull(); const before = el.value; expect(el.inputMode).toBe('numeric'); expect(noConstraints(el)).toBe(true); expect(el.value).toBe(before); });
// SPECSFY: US-006 FR-015 NFR-006 AC-030 TC-011
test('AC-030 sono usa decimal sem restringir conteúdo', () => { const { window } = render(); const el = window.document.querySelector('#finishSleepHours'); expect(el).not.toBeNull(); const before = el.value; expect(el.inputMode).toBe('decimal'); expect(noConstraints(el)).toBe(true); expect(el.value).toBe(before); });
// SPECSFY: US-006 FR-016 NFR-006 AC-031 TC-012
test('AC-031 editor DOM acessível exige overlay fixo e ações de 44px', () => { const { window } = render(); window.editProfileModal(); const editor = window.document.querySelector('[data-profile-editor]'); expect(editor).not.toBeNull(); const editorStyle = window.getComputedStyle(editor); expect(editorStyle.position).toBe('fixed'); expect(Number.parseInt(editorStyle.zIndex || '0', 10)).toBeGreaterThan(10); expect(editor.getAttribute('role')).toBe('dialog'); expect(editor.getAttribute('aria-modal')).toBe('true'); const weight = editor.querySelector('[data-profile-field="weight"] input'); expect(weight).not.toBeNull(); expect(editor.querySelector(`label[for="${weight.id}"]`)).not.toBeNull(); expect(weight.type).toBe('text'); expect(weight.inputMode).toBe('decimal'); expect(window.document.activeElement).toBe(weight); const style = window.getComputedStyle(weight); expect(Number.parseFloat(style.fontSize)).toBeGreaterThanOrEqual(16); expect(Math.max(parseFloat(style.minHeight)||0, parseFloat(style.height)||0)).toBeGreaterThanOrEqual(44); const confirmWeight = editor.querySelector('[data-profile-field="weight"] [data-action="confirm"]'); expect(confirmWeight).not.toBeNull(); const cancelWeight = editor.querySelector('[data-profile-field="weight"] [data-action="cancel"]'); expect(cancelWeight).not.toBeNull(); for (const action of [confirmWeight, cancelWeight]) { const actionStyle = window.getComputedStyle(action); expect(Math.max(parseFloat(actionStyle.minHeight)||0, parseFloat(actionStyle.height)||0)).toBeGreaterThanOrEqual(44); } cancelWeight.click(); const waist = window.document.querySelector('[data-profile-field="waist"] input'); expect(waist).not.toBeNull(); expect(waist.type).toBe('text'); expect(waist.inputMode).toBe('decimal'); expect(window.document.querySelector(`[data-profile-field="waist"] label[for="${waist.id}"]`)).not.toBeNull(); expect(window.document.activeElement).toBe(waist); const waistStyle = window.getComputedStyle(waist); expect(Number.parseFloat(waistStyle.fontSize)).toBeGreaterThanOrEqual(16); expect(Math.max(parseFloat(waistStyle.minHeight)||0, parseFloat(waistStyle.height)||0)).toBeGreaterThanOrEqual(44); const confirmWaist = editor.querySelector('[data-profile-field="waist"] [data-action="confirm"]'); expect(confirmWaist).not.toBeNull(); const cancelWaist = editor.querySelector('[data-profile-field="waist"] [data-action="cancel"]'); expect(cancelWaist).not.toBeNull(); for (const action of [confirmWaist, cancelWaist]) { const actionStyle = window.getComputedStyle(action); expect(Math.max(parseFloat(actionStyle.minHeight)||0, parseFloat(actionStyle.height)||0)).toBeGreaterThanOrEqual(44); } });
// SPECSFY: US-006 FR-016 NFR-006 AC-032 TC-013
test('AC-032 confirma as duas etapas e persiste/renderiza uma vez', () => { const { window } = render(); let persisted = 0; let rendered = 0; window.persist = () => { persisted += 1; }; window.renderProfileSummary = () => { rendered += 1; }; window.editProfileModal(); const w = window.document.querySelector('[data-profile-field="weight"] input'); expect(w).not.toBeNull(); w.value = '80'; const wc = window.document.querySelector('[data-profile-field="weight"] [data-action="confirm"]'); expect(wc).not.toBeNull(); wc.click(); expect(persisted).toBe(0); expect(rendered).toBe(0); const c = window.document.querySelector('[data-profile-field="waist"] input'); expect(c).not.toBeNull(); c.value = '99'; const cc = window.document.querySelector('[data-profile-field="waist"] [data-action="confirm"]'); expect(cc).not.toBeNull(); cc.click(); expect(window.eval('state.profile.weight_kg')).toBe(80); expect(window.eval('state.profile.waist_cm')).toBe(99); expect(persisted).toBe(1); expect(rendered).toBe(1); });
// SPECSFY: US-006 FR-016 NFR-006 AC-033 TC-014
test('AC-033 cancela Peso preserva valor e avança Cintura', () => { const { window } = render(); let persisted = 0; let rendered = 0; window.persist = () => { persisted += 1; }; window.renderProfileSummary = () => { rendered += 1; }; window.editProfileModal(); expect(persisted).toBe(0); expect(rendered).toBe(0); const cancel = window.document.querySelector('[data-profile-field="weight"] [data-action="cancel"]'); expect(cancel).not.toBeNull(); cancel.click(); expect(persisted).toBe(0); expect(rendered).toBe(0); const waist = window.document.querySelector('[data-profile-field="waist"] input'); expect(waist).not.toBeNull(); expect(window.document.activeElement).toBe(waist); const confirm = window.document.querySelector('[data-profile-field="waist"] [data-action="confirm"]'); expect(confirm).not.toBeNull(); confirm.click(); expect(window.eval('state.profile.weight_kg')).toBe('79'); expect(persisted).toBe(1); expect(rendered).toBe(1); });
// SPECSFY: US-006 FR-016 NFR-006 AC-034 TC-015
test('AC-034 confirma Peso e cancela Cintura preservando-a', () => { const { window } = render(); let persisted = 0; let rendered = 0; window.persist = () => { persisted += 1; }; window.renderProfileSummary = () => { rendered += 1; }; window.editProfileModal(); const w = window.document.querySelector('[data-profile-field="weight"] input'); expect(w).not.toBeNull(); w.value = '81'; const wc = window.document.querySelector('[data-profile-field="weight"] [data-action="confirm"]'); expect(wc).not.toBeNull(); wc.click(); expect(persisted).toBe(0); expect(rendered).toBe(0); const cancel = window.document.querySelector('[data-profile-field="waist"] [data-action="cancel"]'); expect(cancel).not.toBeNull(); cancel.click(); expect(window.eval('state.profile.weight_kg')).toBe(81); expect(window.eval('state.profile.waist_cm')).toBe('98'); expect(persisted).toBe(1); expect(rendered).toBe(1); expect(window.document.querySelector('[data-profile-editor]')).toBeNull(); });
// SPECSFY: US-006 FR-016 NFR-006 AC-035 TC-016
test('AC-035 vazio=0, inválido=NaN/null e legado só converte ao confirmar', () => { const { window } = render(); expect(window.eval('state.profile.weight_kg')).toBe('79'); expect(window.eval('state.profile.waist_cm')).toBe('98'); window.editProfileModal(); const w = window.document.querySelector('[data-profile-field="weight"] input'); expect(w).not.toBeNull(); expect(w.value).toBe('79'); w.value = ''; const wc = window.document.querySelector('[data-profile-field="weight"] [data-action="confirm"]'); expect(wc).not.toBeNull(); wc.click(); expect(window.eval('state.profile.weight_kg')).toBe(0); expect(window.eval('state.profile.waist_cm')).toBe('98'); const c = window.document.querySelector('[data-profile-field="waist"] input'); expect(c).not.toBeNull(); c.value = 'abc'; const cc = window.document.querySelector('[data-profile-field="waist"] [data-action="confirm"]'); expect(cc).not.toBeNull(); cc.click(); expect(Number.isNaN(window.eval('state.profile.waist_cm'))).toBe(true); const saved = window.localStorage.getItem('treino_hibrido_juarez_v5'); expect(saved).not.toBeNull(); const parsed = JSON.parse(saved); expect(parsed.profile.weight_kg).toBe(0); expect(parsed.profile.waist_cm).toBeNull(); });
// SPECSFY: US-006 FR-016 NFR-006 AC-036 TC-017
test('AC-036 mantém paridade integral dos HTMLs', async () => { const standalone = await readFile(new URL('../treino_hibrido_juarez_v3_standalone.html', import.meta.url), 'utf8'); expect(standalone.replace(/\r\n/g, '\n')).toBe(html.replace(/\r\n/g, '\n')); });
