import { readFile } from 'node:fs/promises';
import { afterEach, expect, test, vi } from 'vitest';
import { JSDOM } from 'jsdom';
const html = await readFile(new URL('../index.html', import.meta.url), 'utf8'); const windows=[];
function render(){let currentNow=100000;let intervals=0;const dom=new JSDOM(html,{runScripts:'dangerously',url:'http://localhost/',beforeParse(w){w.localStorage.setItem('treino_hibrido_juarez_v5',JSON.stringify({profile:{name:'Legado'},sessions:[],onboardingSeen:true}));w.scrollTo=()=>{};const NativeDate=w.Date;w.Date=class extends NativeDate{static now(){return currentNow;}};const nativeSetInterval=w.setInterval.bind(w);w.setInterval=(...args)=>{intervals+=1;return nativeSetInterval(...args);};Object.defineProperty(w.navigator,'serviceWorker',{configurable:true,value:{register:()=>Promise.resolve()}});}});const r={window:dom.window,document:dom.window.document,advance(ms){currentNow+=ms;r.window.updateRunnerRestTick();},intervals:()=>intervals};windows.push(r);r.window.startWorkoutByKey('segunda');return r;}
afterEach(()=>{vi.restoreAllMocks();while(windows.length)windows.pop().window.close();});
// SPECSFY: US-001 FR-001 NFR-001 AC-001
test('transporta a última série ativa e pausada preservando restante após Retomar',()=>{const{window,document,advance}=render();window.toggleCompleteSet(0,2,90);advance(12000);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:18');window.navigateExercise(1);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:18');window.toggleRunnerRest();window.navigateExercise(1);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:18');expect(document.querySelector('#btnToggleRest').textContent).toBe('Retomar');window.toggleRunnerRest();advance(1000);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:17');});
// SPECSFY: US-001 FR-001 NFR-001 AC-002
test('avança até o terceiro exercício mantendo origem de 90s sem novo intervalo',()=>{const{window,document,intervals}=render();window.toggleCompleteSet(0,2,90);const before=intervals();window.navigateExercise(1);window.navigateExercise(1);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:30');expect(intervals()).toBe(before);});
// SPECSFY: US-001 FR-001 NFR-001 AC-003
test('não transporta timer manual, descanso normal da série 0, DOM novo ou Concluir Treino',()=>{const{window,document}=render();window.startRunnerRestTimer(75);window.navigateExercise(1);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:30');window.navigateExercise(-1);window.toggleCompleteSet(0,0,90);window.navigateExercise(1);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:30');const reloaded=render();expect(reloaded.document.querySelector('#runnerTimerLabel').textContent).toBe('Tempo de Descanso');for(let i=0;i<8;i+=1)window.navigateExercise(1);expect(document.querySelector('#finishWorkoutModal').classList.contains('active')).toBe(true);});
// SPECSFY: US-001 FR-001 NFR-001 AC-001
test('usa o último índice real quando o exercício possui quatro séries',()=>{const{window,document,advance}=render();window.eval('activeWorkout.exerciseData[0].sets.push({setNum:4,weight:"",reps:"",done:false})');window.toggleCompleteSet(0,3,90);advance(12000);window.navigateExercise(1);expect(document.querySelector('#runnerTimerDisplay').textContent).toBe('01:18');});
// SPECSFY: US-001 FR-001 NFR-001 AC-003
test('desmarcar a última série antes de avançar impede o transporte',()=>{const{window,document}=render();window.toggleCompleteSet(0,2,90);window.toggleCompleteSet(0,2,90);window.navigateExercise(1);expect(document.querySelector('#runnerTimerLabel').textContent).toBe('Tempo de Descanso');});
// SPECSFY: US-001 FR-001 NFR-001 AC-003
test('finalizar descanso elegível limpa transporte na próxima tela',()=>{const first=render();first.window.toggleCompleteSet(0,2,1);first.window.finishRunnerRest();first.window.navigateExercise(1);expect(first.document.querySelector('#runnerTimerLabel').textContent).toBe('Tempo de Descanso');});
// SPECSFY: US-001 FR-001 NFR-001 AC-003
test('pular descanso elegível limpa transporte na próxima tela',()=>{const second=render();second.window.toggleCompleteSet(0,2,1);second.window.skipRunnerRest();second.window.navigateExercise(1);expect(second.document.querySelector('#runnerTimerLabel').textContent).toBe('Tempo de Descanso');});
